server:
  port: 8080
  servlet:
    context-path: /BuildFrame

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}/buildframe?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mysql:
  username: ENC(dXXCUIxztgFktNUO70xpxQ==)
  password: ENC(xxE70KtNnjoHL1Ux9nHt8Q==)
  host: ENC(XlmyGkt5RXIU0bpcDPJ8+8IWTWzstLH0)

mybatis:
  type-aliases-package: com.zmy.demo.entity
  mapper-locations: classpath:mapper/*.xml

springdoc:
  #  packages-to-scan: com.zmy
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    #add password solt value
    #password:

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  config: classpath:logback.xml
  level:
    com.zmy.dao: error

---
spring:
  config:
    activate:
      on-profile: pro

  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    url: jdbc:mysql://${mysql.host}/buildframe?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mysql:
  username: ENC(8oih0Xx/5ECLBftOs/KwQQ==)
  password: ENC(jGtNfMhRHY1kULn8Hl43ihWsS1UA6EwC)
  host: ENC(dikcaILS5Gxkw0+SX0G34imAXFcS7dGD2muKUxqIA9c=)

mybatis:
  type-aliases-package: com.zmy.demo.entity
  mapper-locations: classpath:mapper/*.xml

springdoc:
#  packages-to-scan: com.zmy
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

#  group-configs:
#    - group: 'UserManager'
#      paths-to-match: '/user/**'
#      packages-to-scan: com.zmy.controller
#    - group: "ResourceManager"
#      paths-to-match: '/resource/**'
#      packages-to-scan: com.zmy.controller

#knife4j增强配置,可选
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  config: classpath:logback.xml
  level:
    com.zmy.dao: error

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    #add password solt value
    #password:

---
spring:
  config:
    activate:
      on-profile: test





