server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  profiles:
    active: pro

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: ****
    password: ****
    url: jdbc:mysql://localhost:3306/****?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.zmy.demo.entity
  mapper-locations: classpath:mapper/*.xml

springdoc:
  #  packages-to-scan: com.zmy
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true



---
spring:
  config:
    activate:
      on-profile: pro

  datasource:
    username: *****
    password: *****
    url: jdbc:mysql://localhost:3306/****?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.zmy.demo.entity
  mapper-locations: classpath:mapper/*.xml

springdoc:
#  packages-to-scan: com.zmy
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

#  group-configs:
#    - group: 'UserManager'
#      paths-to-match: '/user/**'
#      packages-to-scan: com.zmy.controller
#    - group: "ResourceManager"
#      paths-to-match: '/resource/**'
#      packages-to-scan: com.zmy.controller

#knife4j增强配置,可选
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  config: classpath:logback.xml
  level:
    com.zmy.dao: debug


---
spring:
  config:
    activate:
      on-profile: test





